// Convert an OpenAPI 3 document (parsed JSON) into a runnable two-go test
// suite, returned as a source string. One test per operation, asserting the
// documented 2xx status. JSON input only for now.

const VERBS = ["get", "put", "post", "patch", "delete", "head", "options"];

// Build a two-go suite source from an OpenAPI 3 spec object.
export function fromOpenapi(spec, options = {}) {
  const title = (spec && spec.info && spec.info.title) || "api";
  const baseUrl =
    options.baseUrl ||
    (spec && Array.isArray(spec.servers) && spec.servers[0] && spec.servers[0].url) ||
    "";
  const paths = (spec && spec.paths) || {};

  const lines = [];
  lines.push(`// Generated by two-go from OpenAPI "${title}". Edit freely.`);
  lines.push(`import { go, suite } from "two-go";`);
  lines.push("");
  lines.push(`const api = go(process.env.BASE_URL || ${JSON.stringify(baseUrl)});`);
  lines.push("");
  lines.push(`suite(${JSON.stringify(title)}, ({ test }) => {`);
  for (const rawPath of Object.keys(paths)) {
    const pathItem = paths[rawPath] || {};
    for (const method of VERBS) {
      const op = pathItem[method];
      if (!op) continue;
      for (const line of renderTest(method, rawPath, op)) lines.push("  " + line);
      lines.push("");
    }
  }
  lines.push("});");
  return lines.join("\n") + "\n";
}

function renderTest(method, rawPath, op) {
  const status = successStatus(op.responses);
  const hasParams = /\{[^}]+\}/.test(rawPath);
  const path = rawPath.replace(/\{[^}]+\}/g, "1"); // sample value for path params
  const title = op.operationId || op.summary || `${method.toUpperCase()} ${rawPath}`;

  const out = [];
  out.push(`test(${JSON.stringify(title)}, async () => {`);
  if (hasParams) out.push(`  // path params replaced with sample "1"; adjust as needed`);
  out.push(`  await api.${method}(${JSON.stringify(path)})`);
  if (hasJsonBody(op)) out.push(`    .json({}) // TODO: fill request body`);
  out.push(`    .expectStatus(${status});`);
  out.push("});");
  return out;
}

// First documented 2xx response code, defaulting to 200.
function successStatus(responses) {
  if (responses) {
    for (const code of Object.keys(responses)) {
      if (/^2\d\d$/.test(code)) return Number(code);
    }
  }
  return 200;
}

function hasJsonBody(op) {
  return Boolean(
    op.requestBody && op.requestBody.content && op.requestBody.content["application/json"]
  );
}
