// Convert a Postman v2.1 collection (parsed JSON) into a runnable two-go test
// suite, returned as a source string. JSON input only for now.

const VERBS = new Set(["get", "put", "post", "patch", "delete", "head", "options"]);

// Build a two-go suite source from a Postman collection object.
export function fromPostman(collection, options = {}) {
  const name = (collection && collection.info && collection.info.name) || "imported";
  const baseUrl = options.baseUrl || "";

  const requests = [];
  collectItems((collection && collection.item) || [], requests);

  const lines = [];
  lines.push(`// Generated by two-go from Postman collection "${name}". Edit freely.`);
  lines.push(`import { go, suite } from "two-go";`);
  lines.push("");
  lines.push(`const api = go(process.env.BASE_URL || ${JSON.stringify(baseUrl)});`);
  lines.push("");
  lines.push(`suite(${JSON.stringify(name)}, ({ test }) => {`);
  for (const item of requests) {
    for (const line of renderTest(item)) lines.push("  " + line);
    lines.push("");
  }
  lines.push("});");
  return lines.join("\n") + "\n";
}

// Recursively flatten folders into a flat list of request items.
function collectItems(items, out) {
  for (const item of items) {
    if (item && Array.isArray(item.item)) {
      collectItems(item.item, out);
    } else if (item && item.request) {
      out.push(item);
    }
  }
}

function renderTest(item) {
  const req = item.request;
  const method = String(req.method || "GET").toLowerCase();
  const verb = VERBS.has(method) ? method : "get";
  const path = extractPath(req.url);
  const title = item.name || `${method.toUpperCase()} ${path}`;

  const out = [];
  out.push(`test(${JSON.stringify(title)}, async () => {`);
  out.push(`  await api.${verb}(${JSON.stringify(path)})`);

  const headers = extractHeaders(req.header);
  if (Object.keys(headers).length > 0) out.push(`    .headers(${JSON.stringify(headers)})`);

  const body = extractBody(req.body);
  if (body) out.push(`    ${body}`);

  out.push(`    .expectOk(); // TODO: tighten assertions`);
  out.push("});");
  return out;
}

// Derive a request path from a Postman url (string or object), dropping the
// origin and query, and stripping a leading {{baseUrl}} style variable.
function extractPath(url) {
  if (!url) return "/";
  if (typeof url === "object") {
    if (Array.isArray(url.path)) return "/" + url.path.join("/");
    url = url.raw || "";
  }
  let s = String(url).split("?")[0];
  if (/^https?:\/\//i.test(s)) {
    try {
      return new URL(s).pathname || "/";
    } catch {
      // fall through to manual stripping
    }
  }
  s = s.replace(/^\{\{[^}]+\}\}/, "");
  if (!s.startsWith("/")) s = "/" + s;
  return s || "/";
}

function extractHeaders(header) {
  const out = {};
  if (Array.isArray(header)) {
    for (const h of header) {
      if (h && h.key && !h.disabled) out[h.key] = h.value != null ? String(h.value) : "";
    }
  }
  return out;
}

// Map a Postman body to the matching two-go body call, or "" when unsupported.
function extractBody(body) {
  if (!body) return "";
  if (body.mode === "raw" && body.raw) {
    try {
      return `.json(${JSON.stringify(JSON.parse(body.raw))})`;
    } catch {
      return `.text(${JSON.stringify(body.raw)})`;
    }
  }
  if (body.mode === "urlencoded" && Array.isArray(body.urlencoded)) {
    const obj = {};
    for (const p of body.urlencoded) {
      if (p && p.key && !p.disabled) obj[p.key] = p.value != null ? String(p.value) : "";
    }
    return `.form(${JSON.stringify(obj)})`;
  }
  return "";
}
